### ISSUE TITLE
BookToMessages.toml

### ISSUE THREAD

**Issue by Splamy** [ReSpeak/tsdeclarations#33]
Prototype for setter geneation

```toml
# As in M2B from/to properties can be automatically mapped when they have
# the same high-level name.

[[rule]]
# From the Book
from = "Channel"
# Into message
to = "ChannelEdit"
operation = "update"
# Can be often empty
# Can be inferred from required message parameters
ids = []
properties = [
	{ from="ChannelName", to="ChannelName" },
	# Function which reads a value form the book and splits it up
	# into multiple message parameters
	{ from="MaxClientChannelInheritedFactoryGenerator" function="Bla", tolist=["asd"] }
]

[[rule]]
# From the Book
from = "Client"
# Into message
to = "ClientEdit"
operation = "update"
```
